<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\{Article,Artist,Category,Site}; use App\Services\ImageUploadService; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str; use Illuminate\Validation\Rule;
class ArticleController extends Controller {
 public function index(Request $r){$articles=Article::with(['site','artist','category','author'])->when($r->filled('status'),fn($q)=>$q->where('status',$r->status))->when($r->filled('q'),fn($q)=>$q->where('title','like','%'.$r->q.'%'))->latest()->paginate(20)->withQueryString();return view('admin.articles.index',compact('articles'));}
 public function create(){return view('admin.articles.form',$this->lookups()+['article'=>new Article(['status'=>'draft'])]);}
 public function store(Request $r,ImageUploadService $images){$data=$this->validated($r);$data['user_id']=$r->user()->id;$data['slug']=$this->slug($data['site_id'],$data['title'],$data['slug']??null);if($r->hasFile('featured_image_file')){$up=$images->store($r->file('featured_image_file'),'articles');$data['featured_image']=$up['path'];}$this->normalizePublish($data);$a=Article::create($data);return redirect()->route('admin.articles.edit',$a)->with('ok','Article created.');}
 public function edit(Article $article){return view('admin.articles.form',$this->lookups()+compact('article'));}
 public function preview(Article $article){$article->load(['artist','category','author']);$related=Article::where('site_id',$article->site_id)->whereKeyNot($article->id)->latest()->take(4)->get();return view('articles.show',compact('article','related'));}
 public function update(Request $r,Article $article,ImageUploadService $images){$data=$this->validated($r,$article);$data['slug']=$this->slug($data['site_id'],$data['title'],$data['slug']??null,$article->id);if($r->hasFile('featured_image_file')){if($article->featured_image)Storage::disk('public')->delete($article->featured_image);$up=$images->store($r->file('featured_image_file'),'articles');$data['featured_image']=$up['path'];}$this->normalizePublish($data);$article->update($data);return back()->with('ok','Article saved.');}
 public function destroy(Article $article){if($article->featured_image)Storage::disk('public')->delete($article->featured_image);$article->delete();return redirect()->route('admin.articles.index')->with('ok','Article deleted.');}
 private function validated(Request $r,?Article $a=null):array{return $r->validate(['site_id'=>['required','exists:sites,id'],'artist_id'=>['nullable','exists:artists,id'],'category_id'=>['nullable','exists:categories,id'],'title'=>['required','string','max:255'],'slug'=>['nullable','string','max:255'],'excerpt'=>['nullable','string','max:800'],'body'=>['required','string'],'featured_image_file'=>['nullable','image','max:8192'],'youtube_url'=>['nullable','url','max:500'],'seo_title'=>['nullable','string','max:255'],'meta_description'=>['nullable','string','max:320'],'facebook_hook'=>['nullable','string','max:1500'],'status'=>['required',Rule::in(['draft','review','scheduled','published'])],'published_at'=>['nullable','date'],'featured'=>['nullable','boolean']]);}
 private function lookups():array{return ['sites'=>Site::where('active',true)->orderBy('name')->get(),'artists'=>Artist::orderBy('name')->get(),'categories'=>Category::orderBy('name')->get()];}
 private function slug(int $siteId,string $title,?string $input=null,?int $ignore=null):string{$base=Str::slug($input?:$title)?:Str::random(8);$slug=$base;$i=2;while(Article::where('site_id',$siteId)->where('slug',$slug)->when($ignore,fn($q)=>$q->whereKeyNot($ignore))->exists()){$slug=$base.'-'.$i++;}return $slug;}
 private function normalizePublish(array &$d):void{$d['featured']=!empty($d['featured']);if($d['status']==='published' && empty($d['published_at']))$d['published_at']=now();if($d['status']==='scheduled' && empty($d['published_at']))$d['published_at']=now()->addHour();if(in_array($d['status'],['draft','review'],true))$d['published_at']=$d['published_at']??null;}
}
